// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(TravelContext))]
    partial class TravelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Travel.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            City = "New York",
                            Country = "USA",
                            Description = "Great",
                            Rating = 9
                        },
                        new
                        {
                            ReviewId = 2,
                            City = "Paris",
                            Country = "France",
                            Description = "Great",
                            Rating = 9
                        },
                        new
                        {
                            ReviewId = 3,
                            City = "Seoul",
                            Country = "South Korea",
                            Description = "Great",
                            Rating = 9
                        },
                        new
                        {
                            ReviewId = 4,
                            City = "Milan",
                            Country = "Italy",
                            Description = "Great",
                            Rating = 9
                        },
                        new
                        {
                            ReviewId = 5,
                            City = "Hong Kong",
                            Country = "China",
                            Description = "Great",
                            Rating = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
